# Generated by Django 2.2.5 on 2019-10-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191022_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tile',
            field=models.CharField(default='DEFAULT TILE', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
    ]
