# Generated by Django 2.2.5 on 2019-10-23 20:30

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20191022_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='DEFAULT TITLE', max_length=50)),
                ('item_description', models.CharField(default='DEFAULT DESCRIPTION', max_length=50)),
                ('is_key', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='items',
            field=jsonfield.fields.JSONField(default=dict, max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='items',
            field=jsonfield.fields.JSONField(default=dict, max_length=200),
        ),
    ]
